---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key.
  when: docker_add_repo | bool
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Add Docker repository.
  when: docker_add_repo | bool
  ansible.builtin.get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: /etc/yum.repos.d/docker-{{ docker_edition }}.repo
    owner: root
    group: root
    mode: 420

- name: Configure Docker Nightly repo.
  when: docker_add_repo | bool
  community.general.ini_file:
    dest: /etc/yum.repos.d/docker-{{ docker_edition }}.repo
    section: docker-{{ docker_edition }}-nightly
    option: enabled
    value: "{{ docker_yum_repo_enable_nightly }}"
    mode: 420
    no_extra_spaces: true

- name: Configure Docker Test repo.
  when: docker_add_repo | bool
  community.general.ini_file:
    dest: /etc/yum.repos.d/docker-{{ docker_edition }}.repo
    section: docker-{{ docker_edition }}-test
    option: enabled
    value: "{{ docker_yum_repo_enable_test }}"
    mode: 420
    no_extra_spaces: true

- name: Configure containerd on RHEL 8.
  block:
    - name: Ensure runc is not installed.
      ansible.builtin.package:
        name: runc
        state: absent

    - name: Ensure container-selinux is installed.
      ansible.builtin.package:
        name: container-selinux
        state: present

    - name: Ensure containerd.io is installed.
      package:
        name: containerd.io
        state: present
  when: ansible_distribution_major_version | int == 8
