---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name:
      - docker
      - docker.io
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  when: docker_add_repo | bool
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')
  ansible.builtin.package:
    name: gnupg2
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    force: false
    checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"
  when: docker_add_repo | bool

- name: Ensure curl is present (on older systems without SNI).
  when: add_repository_key is failed and docker_add_repo | bool
  ansible.builtin.package:
    name: curl
    state: present

- name: Add Docker apt key (alternative for older systems without SNI).
  when: add_repository_key is failed and docker_add_repo | bool
  ansible.builtin.shell: >
    curl -sSL {{ docker_apt_gpg_key }} | apt-key add -

- name: Add Docker repository.
  when: docker_add_repo | bool
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: "{{ docker_apt_filename }}"
    update_cache: true
